services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    networks:
      - external
  caddy:
    container_name: web
    image: caddy:2.8.4
    restart: unless-stopped
    expose:
      - 80
      - 443
    networks:
      - external

networks:
  external:
    external: true
