services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - /data/qdrant:/qdrant/storage
    networks: 
      - lan
  lobe-chat:
    image: lobehub/lobe-chat:latest
    container_name: lobe-chat
    restart: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: sk-xxxx
      OPENAI_PROXY_URL: https://api-proxy.com/v1
      ACCESS_CODE: lobe66
    networks: 
      - lan
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - /data/ollama:/root/.ollama
    enviroment:
      OLLAMA_ORIGINS: "*"
    networks:
      - lan

networks:
  lan:
    external: true

configs:
  qdrant_config:
    content: |
      log_level: INFO      
